### ISSUE TITLE
PalmSens - current channel units prefix: consider current range

### ISSUE THREAD

**Issue by KirillSliozberg** [Scaneva/Scaneva#16]
Consider the actual current range set, let the palmsens (transducer channel) deliver the current in corresponding units. Thus if the current range is set to 100 pA, the current must be delivered in pA, for the current ranges 1, 10 and 100 nA, the units must be nA and so on.

**Comment by PieperC** [comment]
Having a variable scaling of an internal variable makes no sense and will only lead to problems. Scaling the display of current values (in the UI) might be considered again at a later point.

**Comment by KirillSliozberg** [comment]
Displaying currents in nA or pA range as µA with plenty of leading zeroes is not an appropriate thing for manually executed experiments, such as auto-approach. At least for transducer it must be doable. While the data is further recorded in for instance µA, the displayed values must be easily readable.  It is much easier to read 302.1 pA, compared to 0.0003021 µA. This is a huge inconvenience in the case of auto-approach, where the measured current can vary abruptly and the user must keep control over the that.
